@isTest
private without sharing class FSL_UpdateWorkOrder_Test {

    //  ***    Service Tech Team: Test class body is commented out as target class is retired   ***

    // static testmethod void callService(){
    //     RestRequest req = new RestRequest();
    //     RestResponse res = new RestResponse();

    //     string json = '[{"In_Jeopardy__c":false,"FSL_Milestone_Issued_Warning__c":false,"Id":"0WO2D0000001GOlWAM"},{"In_Jeopardy__c":false,"FSL_Milestone_Issued_Warning__c":false,"Id":"0WO2D0000001GOvWAM"},{"In_Jeopardy__c":false,"FSL_Milestone_Issued_Warning__c":false,"Id":"0WO2D000000HQdcWAG"}]';

    //     req.requestURI = '/services/apexrest/fslupdateworkorder/';
    //     req.httpMethod = 'POST';
    //     req.requestBody = Blob.valueof(json);
        
    //     RestContext.request = req;
    //     RestContext.response= res;
           
    //      System.Test.StartTest();
    //        FSL_UpdateWorkOrder.doPost();
    //      System.Test.StopTest();  
    // }

}