/* *
 * @description       : 
 * @author            : Shankar Krishnan
 * @group             : 
 * @last modified on  : 03-15-2021
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
 * Modifications Log 
 * Ver   Date         Author                               Modification
 * 1.0   03-15-2021   Shankar Krishnan   Initial Version
* */

public class FSL_MembershipImpairmentWrapper {
    
    @AuraEnabled
    public String name{get;set;}
    @AuraEnabled
    public String message{get;set;}
}